### ISSUE TITLE
[Error] 'albumartist' is not a valid key

### ISSUE THREAD

**Issue by MartinRenze** [An0nimia/deezloader#16]
On `downloa.download_albumdee("https://www.deezer.com/us/album/105324112", output="/home/ubuntu/Downloads", quality="MP3_320", recursive_quality=True, recursive_download=True, interface=True, zips=True)`

I get the following exception:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.6/site-packages/deezloader/__init__.py", line 596, in download_albumdee
    interface, zips
  File "/home/ubuntu/.local/lib/python3.6/site-packages/deezloader/__init__.py", line 348, in download
    ultimatum(infos[a], detas, name[a], quality)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/deezloader/__init__.py", line 217, in ultimatum
    datas, infos, ids
  File "/home/ubuntu/.local/lib/python3.6/site-packages/deezloader/utils.py", line 168, in write_tags
    tag['albumartist'] = data['ar_album']
  File "/usr/local/lib/python3.6/dist-packages/mutagen-1.30-py3.6.egg/mutagen/_file.py", line 66, in __setitem__
  File "/usr/local/lib/python3.6/dist-packages/mutagen-1.30-py3.6.egg/mutagen/easyid3.py", line 212, in __setitem__
mutagen.easyid3.EasyID3KeyError: "'albumartist' is not a valid key"
`

Only the first song is downloaded

**Comment by An0nimia** [comment]
Last mutagen version is 1.40.0

**Comment by MartinRenze** [comment]
An0nimia, thank you for your fast reply. With mutagen 1.4x everything is working fine.
