### ISSUE TITLE
[Error] on Raspberry Pi 2, Raspberry Pi 3 too

### ISSUE THREAD

**Issue by quatmo** [An0nimia/deezloader#17]
On Raspberry Pi 2
volumio@volumio:~$ sudo python3.7 /usr/local/lib/python3.7/site-packages/deezloader/down.py

downloa.download_albumdee(
	'http://www.deezer.com/album/102689',
	output = '/data/INTERNAL',
	quality='MP3_320', 
	recursive_quality = True,
	recursive_download = True,
	not_interface = False,
	zips = False
)

I get the following exception:
```

  0%|                                                     | 0/7 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/deezloader/down.py", line 13, in <module>
    zips = False
  File "/usr/local/lib/python3.7/site-packages/deezloader/__init__.py", line 597, in download_albumdee
    not_interface, zips
  File "/usr/local/lib/python3.7/site-packages/deezloader/__init__.py", line 354, in download
    ultimatum(infos[a], detas, name[a], quality)
  File "/usr/local/lib/python3.7/site-packages/deezloader/__init__.py", line 188, in ultimatum
    hashs = genurl(md5, quality, ids, infos['MEDIA_VERSION'])
  File "/usr/local/lib/python3.7/site-packages/deezloader/utils.py", line 90, in genurl
    c = AES.new("jo6aey6haid2Teih", AES.MODE_ECB)
  File "/usr/local/lib/python3.7/site-packages/Crypto/Cipher/AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/Crypto/Cipher/__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/Crypto/Cipher/_mode_ecb.py", line 215, in _create_ecb_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "/usr/local/lib/python3.7/site-packages/Crypto/Cipher/AES.py", line 103, in _create_base_cipher
    result = start_operation(c_uint8_ptr(key),
  File "/usr/local/lib/python3.7/site-packages/Crypto/Util/_raw_api.py", line 235, in c_uint8_ptr
    raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <class 'str'> cannot be passed to C code

```

**Comment by An0nimia** [comment]
@quatmo pip3 uninstall pycrypto && apt-get install python3-crypto

**Comment by 9Mad-Max5** [comment]
after all the shit with removing pyhton3.5 this issue now occurs after:
`apt-get install python3-crypto`

`dpkg: Fehler beim Bearbeiten des Paketes python3-crypto (--configure):
 Abhängigkeitsprobleme - verbleibt unkonfiguriert
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von dh-python:
 dh-python hängt ab von python3:any (>= 3.3.2-2~); aber:
  Paket python3 ist noch nicht konfiguriert.

dpkg: Fehler beim Bearbeiten des Paketes dh-python (--configure):
 Abhängigkeitsprobleme - verbleibt unkonfiguriert
Fehler traten auf beim Bearbeiten von:
 python3
 python3-crypto
 dh-python
E: Sub-process /usr/bin/dpkg returned an error code (1)
`

**Comment by An0nimia** [comment]
@9Mad-Max5 It isn't in my domain, is something which is not caused by installing my library

**Comment by 9Mad-Max5** [comment]
Ah sorry for beeing not precise enough.
At the beginning i installed pycryptodome and it should be the same as python3-crypto.

Starting is is quite ok.
But after a download command the following error is set.

`Downloading:Stars - Vize, Laniia
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/deezloader/__init__.py", line 430, in download_trackdee
    not_interface, directory
  File "/usr/local/lib/python3.7/site-packages/deezloader/__init__.py", line 232, in download
    nams = ultimatum(infos, datas, name, quality)
  File "/usr/local/lib/python3.7/site-packages/deezloader/__init__.py", line 137, in ultimatum
    hashs = genurl(md5, quality, ids, infos['MEDIA_VERSION'])
  File "/usr/local/lib/python3.7/site-packages/deezloader/utils.py", line 126, in genurl
    c = AES.new("jo6aey6haid2Teih", AES.MODE_ECB)
  File "/usr/local/lib/python3.7/site-packages/Crypto/Cipher/AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/Crypto/Cipher/__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/Crypto/Cipher/_mode_ecb.py", line 215, in _create_ecb_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "/usr/local/lib/python3.7/site-packages/Crypto/Cipher/AES.py", line 103, in _create_base_cipher
    result = start_operation(c_uint8_ptr(key),
  File "/usr/local/lib/python3.7/site-packages/Crypto/Util/_raw_api.py", line 235, in c_uint8_ptr
    raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <class 'str'> cannot be passed to C code
`

**Comment by 9Mad-Max5** [comment]
@An0nimia your right it is my issue with pycryptodome.
