### ISSUE TITLE
deez-web.py TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by BramFr** [An0nimia/deezloader#2]
I`ll get the following issue.
````bash
 pip3 install deezloader --upgrade
Collecting deezloader
  Downloading https://files.pythonhosted.org/packages/02/0e/36653d7f0726f4dc38017f68ad56580f24ade4414107949396de98b0c02e/deezloader-2021.8.18.tar.gz
Requirement already satisfied, skipping upgrade: mutagen in /home/bram/.local/lib/python3.7/site-packages (from deezloader) (1.45.1)
Requirement already satisfied, skipping upgrade: pycryptodome in /home/bram/.local/lib/python3.7/site-packages (from deezloader) (3.9.8)
Requirement already satisfied, skipping upgrade: requests in /usr/lib/python3/dist-packages (from deezloader) (2.21.0)
Requirement already satisfied, skipping upgrade: spotipy in /home/bram/.local/lib/python3.7/site-packages (from deezloader) (2.16.1)
Requirement already satisfied, skipping upgrade: tqdm in /home/bram/.local/lib/python3.7/site-packages (from deezloader) (4.51.0)
Requirement already satisfied, skipping upgrade: six>=1.10.0 in /usr/lib/python3/dist-packages (from spotipy->deezloader) (1.12.0)
Building wheels for collected packages: deezloader
  Running setup.py bdist_wheel for deezloader ... done
  Stored in directory: /home/bram/.cache/pip/wheels/8b/0c/1d/ae1b7bd8722186d879ab5f10bb42cbfc3a385776c06e71eb82
Successfully built deezloader
Installing collected packages: deezloader
  Found existing installation: deezloader 2020.9.18
    Uninstalling deezloader-2020.9.18:
      Successfully uninstalled deezloader-2020.9.18
Successfully installed deezloader-2021.8.18

deez-web.py -h
Traceback (most recent call last):
  File "/usr/local/bin/deez-web.py", line 11, in <module>
    from deezloader import Login, deezweb_utils
  File "/home/bram/.local/lib/python3.7/site-packages/deezloader/__init__.py", line 3, in <module>
    from .__dee_api__ import API
  File "/home/bram/.local/lib/python3.7/site-packages/deezloader/__dee_api__.py", line 6, in <module>
    from .__utils__ import artist_sort, convert_to_date
  File "/home/bram/.local/lib/python3.7/site-packages/deezloader/__utils__.py", line 5, in <module>
    from .models.track import Track
  File "/home/bram/.local/lib/python3.7/site-packages/deezloader/models/__init__.py", line 3, in <module>
    from .smart import Smart
  File "/home/bram/.local/lib/python3.7/site-packages/deezloader/models/smart.py", line 4, in <module>
    from .album import Album
  File "/home/bram/.local/lib/python3.7/site-packages/deezloader/models/album.py", line 5, in <module>
    class Album:
  File "/home/bram/.local/lib/python3.7/site-packages/deezloader/models/album.py", line 19, in Album
    def tracks(self) -> list[Track]:
TypeError: 'type' object is not subscriptable


 deez-dw.py -h
Traceback (most recent call last):
  File "/usr/local/bin/deez-dw.py", line 4, in <module>
    from deezloader import Login
  File "/home/bram/.local/lib/python3.7/site-packages/deezloader/__init__.py", line 3, in <module>
    from .__dee_api__ import API
  File "/home/bram/.local/lib/python3.7/site-packages/deezloader/__dee_api__.py", line 6, in <module>
    from .__utils__ import artist_sort, convert_to_date
  File "/home/bram/.local/lib/python3.7/site-packages/deezloader/__utils__.py", line 5, in <module>
    from .models.track import Track
  File "/home/bram/.local/lib/python3.7/site-packages/deezloader/models/__init__.py", line 3, in <module>
    from .smart import Smart
  File "/home/bram/.local/lib/python3.7/site-packages/deezloader/models/smart.py", line 4, in <module>
    from .album import Album
  File "/home/bram/.local/lib/python3.7/site-packages/deezloader/models/album.py", line 5, in <module>
    class Album:
  File "/home/bram/.local/lib/python3.7/site-packages/deezloader/models/album.py", line 19, in Album
    def tracks(self) -> list[Track]:
TypeError: 'type' object is not subscriptable
````

**Comment by BramFr** [comment]
upgraded to python3.9 :)
