### ISSUE TITLE
Script crashing

### ISSUE THREAD

**Issue by wmahfoudh** [An0nimia/deezloader#21]
Downloading:Mercy - Duffy
Downloading:Survivor - Destiny's Child
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/deezloader/__init__.py", line 580, in download_playlistdee
    recursive_download, not_interface
  File "/usr/lib/python3.7/site-packages/deezloader/__init__.py", line 367, in download_trackdee
    "http://api.deezer.com/album/" + str(url['album']['id']), True
  File "/usr/lib/python3.7/site-packages/deezloader/utils.py", line 74, in request
    raise exceptions.TrackNotFound("Track not found :(")
deezloader.exceptions.TrackNotFound: Track not found :(

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/deezloader-dw", line 168, in <module>
    recursive_download, not_gui, zips
  File "/usr/bin/deezloader-dw", line 55, in download_link
    recursive_download, not_gui, zips
  File "/usr/lib/python3.7/site-packages/deezloader/__init__.py", line 584, in download_playlistdee
    song = a['title'] + " - " + a['artist']
TypeError: can only concatenate str (not "dict") to str

**Comment by An0nimia** [comment]
@wmahfoudh Send me playlist link

**Comment by wmahfoudh** [comment]
> @wmahfoudh Send me playlist link

https://www.deezer.com/en/playlist/4825491804

**Comment by wmahfoudh** [comment]
here is the cl
deezloader-dw -rq=true -rd=true -q=256 -l=https://www.deezer.com/en/playlist/4825491804

**Comment by An0nimia** [comment]
Update the library and try again :)

**Comment by wmahfoudh** [comment]
Yes, now working perfectly!

**Comment by wmahfoudh** [comment]
Thnaks.

**Comment by An0nimia** [comment]
@wmahfoudh Nada close the issue

**Comment by wmahfoudh** [comment]
Done already !
