### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by geotmt1** [An0nimia/deezloader#6]
this is what I always get in Windows, I do have all the modules.
File ".\ok.py", line 1, in <module>
    import deezloader
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\deezloader\__init__.py", line 7, in <module>
    from Crypto.Hash import MD5
ModuleNotFoundError: No module named 'Crypto'

But even if I force the program to load all the dependecies, I get this:
  0%|          | 0/6 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Computator\Desktop\NIER\stupid.py", line 186, in download
    crypt = self.request(genurl(infos['results']['FALLBACK']['MD5_ORIGIN'], quality, infos['results']['MEDIA_VERSION']))
KeyError: 'FALLBACK'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Computator/Desktop/NIER/dzldr.py", line 42, in <module>
    option(url, output = "C:/Users/Computator/Desktop/NIGGER", check = True, quality = qualit, recursive = True)
  File "C:\Users\Computator\Desktop\NIER\stupid.py", line 333, in download_albumdee
    extension, qualit = self.download(urls[a], dir, quality, recursive)
  File "C:\Users\Computator\Desktop\NIER\stupid.py", line 188, in download
    crypt = self.request(genurl(infos['results']['MD5_ORIGIN'], quality, infos['results']['MEDIA_VERSION']))
  File "C:\Users\Computator\Desktop\NIER\stupid.py", line 135, in genurl
    c = AES.new("jo6aey6haid2Teih", AES.MODE_ECB)
  File "C:\Users\Computator\Desktop\NIER\Crypto\Cipher\AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "C:\Users\Computator\Desktop\NIER\Crypto\Cipher\__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "C:\Users\Computator\Desktop\NIER\Crypto\Cipher\_mode_ecb.py", line 215, in _create_ecb_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "C:\Users\Computator\Desktop\NIER\Crypto\Cipher\AES.py", line 103, in _create_base_cipher
    result = start_operation(c_uint8_ptr(key),
  File "C:\Users\Computator\Desktop\NIER\Crypto\Util\_raw_api.py", line 234, in c_uint8_ptr
    raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <class 'str'> cannot be passed to C code

**Comment by An0nimia** [comment]
First one, I suggest you to use a linux distro for code in python.
Second one, The script have to work on python3
Third one, If you force the library is normal to get error, that lib is not there without any reason you have to install it, I supposed that pycrypto is installated by default. Anyway for resolve this 'from Crypto.Hash import MD5' try pip or pip3 install pycrypto instead for debian like linux system type apt-get install python3-crypto

**Comment by geotmt1** [comment]
It works just fine on rasbian for me but in the README it says that windows is suported.
By force I mean load all the modules needed.
Pycrypto is suported only for python 3.3 and downwards.

**Comment by An0nimia** [comment]
@geotmt1 But I have it on python3.6, what do you mean with force? If module isn't installed how do you force it?

**Comment by geotmt1** [comment]
I copied all the modules in the same folder of with your program and my script (heres the link if you whant to see it https://github.com/geotmt1/pip-deezloader-script) and then pressed run.

**Comment by An0nimia** [comment]
@geotmt1 Okay, close the issue please

**Comment by geotmt1** [comment]
But you haven't done anything, at least remove the windows supported tag.

**Comment by geotmt1** [comment]
Also, I now updated the script and supports all the features from your app.

**Comment by An0nimia** [comment]
@geotmt1 Sounds like a meme😂😂

**Comment by An0nimia** [comment]
@geotmt1 Good for yoi
